server:
  port: 8080
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
log:
  log_level: debug
  file_log_name: "./storages/logs/devabc.log"
  max_size: 500
  max_back_ups: 3
  max_age: 28
  compress: true